In [4]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [ ]:
N_angle = 2

sigma = 1
dx = 0.1
h = sigma*dx

img = complex(0, 1)

def T_m(mu, h):
    return(
        np.array([[mu/h-1, 1],
                  [mu/h, mu/h+1]])
    )

def R_m(mu, h, lam):
    return(
        np.array([[0,0],
                  [0,2*mu/h*np.exp(-img*lam*h)]])
    )

def S():
    S = np.zeros((2*N_angle,2*N_angle)).astype(np.complex_)
    #for m in range(N_angle):

    return(S)

def bar(angles, h, lam):
    T_bar = np.zeros((2*N_angle,2*N_angle)).astype(np.complex_)
    R_bar = np.zeros((2*N_angle,2*N_angle)).astype(np.complex_)

    for m in range(N_angle):
        T_mat = T_m(angles[m], h)
        R_mat = R_m(angles[m], h, lam)


        T_bar[2*m,2*m]     = T_mat[0,0]
        T_bar[2*m,2*m+1]   = T_mat[0,1]
        T_bar[2*m+1,2*m]   = T_mat[1,0]
        T_bar[2*m+1,2*m+1] = T_mat[1,1]

        R_bar[2*m,2*m]     = R_mat[0,0]
        R_bar[2*m,2*m+1]   = R_mat[0,1]
        R_bar[2*m+1,2*m]   = R_mat[1,0]
        R_bar[2*m+1,2*m+1] = R_mat[1,1]

    return(T_bar, R_bar)

def eig_val(angles, h):

    N_lam = 2
    eig_lam = np.zeros(N_lam)
    for i in range(N_lam):
        lam = 2/N_lam * np.pi * i
        T_bar, R_bar = bar(angles,h,lam)
        print(T_bar)
        print(R_bar)
        transport_mat =  np.matmul (np.linalg.inv(T_bar), R_bar)

        eig_val, stand_eig_mat = np.linalg.eig(transport_mat)
        eig_lam[i] = np.max(np.abs(eig_val))
    
    #spec_rad = np.max(eig_lam)

    return(eig_lam)

[angles,weights] = np.polynomial.legendre.leggauss(N_angle)

print(eig_val(angles, h))

[[-6.77350269  1.          0.          0.        ]
 [-5.77350269 -4.77350269  0.          0.        ]
 [ 0.          0.          4.77350269  1.        ]
 [ 0.          0.          5.77350269  6.77350269]]
[[  0.           0.           0.           0.        ]
 [  0.         -11.54700538   0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.          11.54700538]]
[[-6.77350269  1.          0.          0.        ]
 [-5.77350269 -4.77350269  0.          0.        ]
 [ 0.          0.          4.77350269  1.        ]
 [ 0.          0.          5.77350269  6.77350269]]
[[  0.           0.           0.           0.        ]
 [  0.         -10.98185471   0.           0.        ]
 [  0.           0.           0.           0.        ]
 [  0.           0.           0.          10.98185471]]
[2.07530168 1.97372919]


/var/folders/t_/2l4lwvkn537dkvrfy5xmkvc80000gn/T/ipykernel_12100/1861107890.py:41: ComplexWarning: Casting complex values to real discards the imaginary part
  R_bar[2*m,2*m]     = R_mat[0,0]
/var/folders/t_/2l4lwvkn537dkvrfy5xmkvc80000gn/T/ipykernel_12100/1861107890.py:42: ComplexWarning: Casting complex values to real discards the imaginary part
  R_bar[2*m,2*m+1]   = R_mat[0,1]
/var/folders/t_/2l4lwvkn537dkvrfy5xmkvc80000gn/T/ipykernel_12100/1861107890.py:43: ComplexWarning: Casting complex values to real discards the imaginary part
  R_bar[2*m+1,2*m]   = R_mat[1,0]
/var/folders/t_/2l4lwvkn537dkvrfy5xmkvc80000gn/T/ipykernel_12100/1861107890.py:44: ComplexWarning: Casting complex values to real discards the imaginary part
  R_bar[2*m+1,2*m+1] = R_mat[1,1]
